spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: springcloudTotal-config-guotao-dev
---
spring:
  profiles: test
  application:
    name: springcloudTotal-config-guotao-test